name: Build Android APK (No Wrapper)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Download Gradle
        run: |
          set -e
          GRADLE_VERSION="8.7"
          curl -L "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" -o gradle.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-${GRADLE_VERSION}/bin" >> $GITHUB_PATH
          gradle --version

      - name: Build Debug APK (no gradlew)
        working-directory: android
        run: |
          set -e
          ls -la
          gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: "**/app/build/outputs/apk/debug/*.apk"
          
